[project]
name = "generador_mapas"
version = "0.1.0"
description = "Generador de mapas para dungeons de videojuegos 2D"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.2",
    "rich",
]
